<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>XML Sitemap | GetCRX</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            background-color: #121014;
            color: #ece8ee;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 900px;
            margin: 0 auto;
            background: #18151b;
            border: 1px solid #28242d;
            border-radius: 16px;
            padding: 32px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.5);
          }
          .header {
            border-bottom: 1px solid #28242d;
            padding-bottom: 20px;
            margin-bottom: 24px;
            display: flex;
            align-items: center;
            justify-content: space-between;
          }
          h1 {
            color: #e8a33d;
            font-size: 24px;
            margin: 0 0 6px 0;
          }
          p.subtitle {
            color: #928b9a;
            font-size: 13px;
            margin: 0;
          }
          .badge {
            background: rgba(232, 163, 61, 0.15);
            color: #e8a33d;
            border: 1px solid rgba(232, 163, 61, 0.3);
            font-size: 12px;
            padding: 4px 10px;
            border-radius: 6px;
            font-weight: 600;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            font-family: monospace;
          }
          th {
            text-align: left;
            padding: 12px 14px;
            background: #1f1b23;
            color: #e8a33d;
            border-bottom: 1px solid #28242d;
            font-weight: 600;
          }
          td {
            padding: 12px 14px;
            border-bottom: 1px solid #28242d;
            color: #ece8ee;
          }
          tr:hover td {
            background: #231f28;
          }
          a {
            color: #4fb6ae;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority-tag {
            color: #e8a33d;
            font-weight: bold;
          }
          .footer {
            margin-top: 24px;
            font-size: 11px;
            color: #928b9a;
            text-align: right;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div>
              <h1>GetCRX XML Sitemap</h1>
              <p class="subtitle">Search Engine Indexing &amp; URL Manifest for GetCRX</p>
            </div>
            <div class="badge">
              <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>URL Location</th>
                <th>Change Frequency</th>
                <th>Priority</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td style="color: #928b9a;"><xsl:value-of select="position()"/></td>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td><xsl:value-of select="sitemap:changefreq"/></td>
                  <td class="priority-tag"><xsl:value-of select="sitemap:priority"/></td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <div class="footer">
            Generated by GetCRX &bull; Developed by JOJIN JOHN
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
